### ISSUE TITLE
Allow other enumerable types in the Iteration component

### ISSUE THREAD

**Issue by Akinzekeel** [hassanhabib/PrettyBlazor#2]
I've noticed that the Iteration component seems to be hardcoded to only take a List<T>. 

If an ICollection<T> or IEnumerable<T> is provided, for example, the error is also rather confusing.

Would it be possible to allow IEnumerable<T> on the Items parameter? Or is there a specific reason why it has to be List?

**Comment by hassanhabib** [comment]
`IEnumerable` is not supported.
